print("|-----------------------------------|")
print("|     WELCOME TO VISITOR KIOSK      |")
print("|-----------------------------------|")
print("What is your name?")
name= input()
print("What is your organization?")
organization= input()
print("What is your email?")
email= input()
print("What is your access?")
access= input()
print("What is your issuer?")
issuer= input()
print("|-----------------------------------|")
print("|ATTENDEE: " + name.ljust(25) + "|")
print("|ORG     : " + organization.ljust(25) + "|")
print("|CONTACT : " + email.ljust(25) + "|")
print("|ACCESS  : " + access.ljust(25) + "|")
print("|ISSUER  : " + issuer.ljust(25) + "|")
print("|-----------------------------------|")

